In [69]:
## Importing Libraries
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

In [70]:
## Importing Dataset
df = pd.read_csv("50_Startups.csv")
X = df.iloc[:,:-1].values
y = df.iloc[:,-1].values

In [71]:
print(X)

[[165349.2 136897.8 471784.1 'New York']
 [162597.7 151377.59 443898.53 'California']
 [153441.51 101145.55 407934.54 'Florida']
 [144372.41 118671.85 383199.62 'New York']
 [142107.34 91391.77 366168.42 'Florida']
 [131876.9 99814.71 362861.36 'New York']
 [134615.46 147198.87 127716.82 'California']
 [130298.13 145530.06 323876.68 'Florida']
 [120542.52 148718.95 311613.29 'New York']
 [123334.88 108679.17 304981.62 'California']
 [101913.08 110594.11 229160.95 'Florida']
 [100671.96 91790.61 249744.55 'California']
 [93863.75 127320.38 249839.44 'Florida']
 [91992.39 135495.07 252664.93 'California']
 [119943.24 156547.42 256512.92 'Florida']
 [114523.61 122616.84 261776.23 'New York']
 [78013.11 121597.55 264346.06 'California']
 [94657.16 145077.58 282574.31 'New York']
 [91749.16 114175.79 294919.57 'Florida']
 [86419.7 153514.11 0.0 'New York']
 [76253.86 113867.3 298664.47 'California']
 [78389.47 153773.43 299737.29 'New York']
 [73994.56 122782.75 303319.26 'Florida']
 [67532

In [72]:
print(y)

[192261.83 191792.06 191050.39 182901.99 166187.94 156991.12 156122.51
 155752.6  152211.77 149759.96 146121.95 144259.4  141585.52 134307.35
 132602.65 129917.04 126992.93 125370.37 124266.9  122776.86 118474.03
 111313.02 110352.25 108733.99 108552.04 107404.34 105733.54 105008.31
 103282.38 101004.64  99937.59  97483.56  97427.84  96778.92  96712.8
  96479.51  90708.19  89949.14  81229.06  81005.76  78239.91  77798.83
  71498.49  69758.98  65200.33  64926.08  49490.75  42559.73  35673.41
  14681.4 ]


In [73]:
from sklearn.impute import SimpleImputer
si = SimpleImputer(missing_values=np.nan,strategy="mean")
X[:,:3] = si.fit_transform(X[:,:3])
X

array([[165349.2, 136897.8, 471784.1, 'New York'],
       [162597.7, 151377.59, 443898.53, 'California'],
       [153441.51, 101145.55, 407934.54, 'Florida'],
       [144372.41, 118671.85, 383199.62, 'New York'],
       [142107.34, 91391.77, 366168.42, 'Florida'],
       [131876.9, 99814.71, 362861.36, 'New York'],
       [134615.46, 147198.87, 127716.82, 'California'],
       [130298.13, 145530.06, 323876.68, 'Florida'],
       [120542.52, 148718.95, 311613.29, 'New York'],
       [123334.88, 108679.17, 304981.62, 'California'],
       [101913.08, 110594.11, 229160.95, 'Florida'],
       [100671.96, 91790.61, 249744.55, 'California'],
       [93863.75, 127320.38, 249839.44, 'Florida'],
       [91992.39, 135495.07, 252664.93, 'California'],
       [119943.24, 156547.42, 256512.92, 'Florida'],
       [114523.61, 122616.84, 261776.23, 'New York'],
       [78013.11, 121597.55, 264346.06, 'California'],
       [94657.16, 145077.58, 282574.31, 'New York'],
       [91749.16, 114175.79, 29491

In [74]:
##Encoding categorical column

from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder

ct = ColumnTransformer(transformers=[('encoder', OneHotEncoder(drop='first'), [3])], remainder='passthrough')
X = ct.fit_transform(X)
X

array([[0.0, 1.0, 165349.2, 136897.8, 471784.1],
       [0.0, 0.0, 162597.7, 151377.59, 443898.53],
       [1.0, 0.0, 153441.51, 101145.55, 407934.54],
       [0.0, 1.0, 144372.41, 118671.85, 383199.62],
       [1.0, 0.0, 142107.34, 91391.77, 366168.42],
       [0.0, 1.0, 131876.9, 99814.71, 362861.36],
       [0.0, 0.0, 134615.46, 147198.87, 127716.82],
       [1.0, 0.0, 130298.13, 145530.06, 323876.68],
       [0.0, 1.0, 120542.52, 148718.95, 311613.29],
       [0.0, 0.0, 123334.88, 108679.17, 304981.62],
       [1.0, 0.0, 101913.08, 110594.11, 229160.95],
       [0.0, 0.0, 100671.96, 91790.61, 249744.55],
       [1.0, 0.0, 93863.75, 127320.38, 249839.44],
       [0.0, 0.0, 91992.39, 135495.07, 252664.93],
       [1.0, 0.0, 119943.24, 156547.42, 256512.92],
       [0.0, 1.0, 114523.61, 122616.84, 261776.23],
       [0.0, 0.0, 78013.11, 121597.55, 264346.06],
       [0.0, 1.0, 94657.16, 145077.58, 282574.31],
       [1.0, 0.0, 91749.16, 114175.79, 294919.57],
       [0.0, 1.0, 86419.7

In [75]:
##Train test split

from sklearn.model_selection import train_test_split
train_X, test_X, train_y, test_y = train_test_split(X, y, test_size=0.2)

In [76]:
print(train_X)

[[0.0 0.0 0.0 135426.92 0.0]
 [0.0 0.0 28754.33 118546.05 172795.67]
 [1.0 0.0 142107.34 91391.77 366168.42]
 [1.0 0.0 93863.75 127320.38 249839.44]
 [0.0 0.0 123334.88 108679.17 304981.62]
 [0.0 0.0 64664.71 139553.16 137962.62]
 [0.0 1.0 86419.7 153514.11 0.0]
 [0.0 1.0 46014.02 85047.44 205517.64]
 [1.0 0.0 67532.53 105751.03 304768.73]
 [0.0 0.0 76253.86 113867.3 298664.47]
 [1.0 0.0 91749.16 114175.79 294919.57]
 [0.0 1.0 77044.01 99281.34 140574.81]
 [0.0 0.0 78013.11 121597.55 264346.06]
 [1.0 0.0 119943.24 156547.42 256512.92]
 [0.0 0.0 162597.7 151377.59 443898.53]
 [1.0 0.0 75328.87 144135.98 134050.07]
 [1.0 0.0 61994.48 115641.28 91131.24]
 [0.0 1.0 1000.23 124153.04 1903.93]
 [0.0 0.0 22177.74 154806.14 28334.72]
 [1.0 0.0 130298.13 145530.06 323876.68]
 [0.0 0.0 0.0 116983.8 45173.06]
 [0.0 0.0 23640.93 96189.63 148001.11]
 [0.0 1.0 94657.16 145077.58 282574.31]
 [1.0 0.0 27892.92 84710.77 164470.71]
 [0.0 1.0 61136.38 152701.92 88218.23]
 [1.0 0.0 1315.46 115816.21 29711

In [77]:
print(test_X)

[[0.0 0.0 91992.39 135495.07 252664.93]
 [0.0 1.0 131876.9 99814.71 362861.36]
 [1.0 0.0 66051.52 182645.56 118148.2]
 [1.0 0.0 73994.56 122782.75 303319.26]
 [0.0 0.0 134615.46 147198.87 127716.82]
 [1.0 0.0 55493.95 103057.49 214634.81]
 [0.0 1.0 78389.47 153773.43 299737.29]
 [0.0 0.0 100671.96 91790.61 249744.55]
 [0.0 0.0 46426.07 157693.92 210797.67]
 [0.0 1.0 72107.6 127864.55 353183.81]]


In [78]:
print(train_y)

[ 42559.73  78239.91 166187.94 141585.52 149759.96 107404.34 122776.86
  96479.51 108733.99 118474.03 124266.9  108552.04 126992.93 132602.65
 191792.06 105733.54  99937.59  64926.08  65200.33 155752.6   14681.4
  71498.49 125370.37  77798.83  97483.56  49490.75  69758.98 101004.64
  81229.06  89949.14  97427.84  81005.76  90708.19 192261.83 152211.77
 146121.95  35673.41 129917.04 182901.99 191050.39]


In [79]:
print(test_y)

[134307.35 156991.12 103282.38 110352.25 156122.51  96778.92 111313.02
 144259.4   96712.8  105008.31]


In [80]:
##Training on Train set
from sklearn.linear_model import LinearRegression

regressor = LinearRegression()
regressor.fit(train_X, train_y)

LinearRegression()

In [81]:
#Testing on test set

y_pred = regressor.predict(test_X)
print(np.concatenate((y_pred.reshape(-1,1),test_y.reshape(-1,1)), axis=-1))

[[125939.28715005 134307.35      ]
 [165473.46179251 156991.12      ]
 [101597.46482047 103282.38      ]
 [116005.19350898 110352.25      ]
 [154218.16592915 156122.51      ]
 [ 98514.22644332  96778.92      ]
 [120287.61253326 111313.02      ]
 [133407.31178869 144259.4       ]
 [ 88337.98212335  96712.8       ]
 [117907.68618409 105008.31      ]]


In [82]:
##Measuring the performance
from sklearn.metrics import r2_score
print(r2_score(test_y, y_pred))

0.8810554098802109


In [83]:
d1 = y_pred - test_y
d2 = y_pred - test_y.mean()
r_squared = 1 - (d1.dot(d1)/d2.dot(d2))
r_squared

0.8818828729900751

In [95]:
## Using k-fold cross validation
from sklearn.model_selection import cross_val_score

scores = cross_val_score(regressor, train_X, train_y, scoring="r2", cv=5)
print(scores)
print(scores.mean())
print(scores.std())


[0.95974976 0.82098981 0.87839569 0.77317085 0.92473977]
0.8714091782955137
0.06766077623532518


In [85]:
regressor.coef_


array([ 1.94516581e+03,  3.50082922e+03,  7.81004120e-01, -1.83350759e-02,
        3.83785272e-02])

In [89]:
regressor.predict([[1.0, 0.0, 66051.52, 182645.56, 118148.2]])

array([101597.46482047])

In [88]:
np.dot([1.0,1.0, 0.0, 66051.52, 182645.56, 118148.2],np.array([regressor.intercept_]+list(regressor.coef_)))

101597.46482046762

In [96]:
## Saving model
import pickle
pickle.dump(regressor, open('startup.pkl', 'wb') )