In [9]:
import pandas as pd
import numpy as np

In [10]:
df = pd.read_csv('cleaned_data.csv')

In [11]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2770409 entries, 0 to 2770408
Data columns (total 5 columns):
 #   Column          Dtype  
---  ------          -----  
 0   Unnamed: 0      int64  
 1   amount          float64
 2   newbalanceDest  float64
 3   type_encoded    int64  
 4   isFraud         int64  
dtypes: float64(2), int64(3)
memory usage: 105.7 MB


In [12]:
df.isna().sum()

Unnamed: 0        0
amount            0
newbalanceDest    0
type_encoded      0
isFraud           0
dtype: int64

In [13]:
df.drop(['Unnamed: 0'],axis = 1,inplace = True)

In [14]:
df.dropna(inplace=True)

In [15]:
X = df.iloc[:,0:-1]
y = df.iloc[:,-1]

In [16]:
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report

In [17]:
# Train-test split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# Standardize the features
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

In [18]:
from sklearn.linear_model import LogisticRegression

# Model
lr = LogisticRegression()
lr.fit(X_train, y_train)

# Predictions
y_pred = lr.predict(X_test)

# Evaluation
print("Logistic Regression")
print("Accuracy:", accuracy_score(y_test, y_pred))
print(confusion_matrix(y_test, y_pred))
print(classification_report(y_test, y_pred))

Logistic Regression
Accuracy: 0.9971845322533488
[[552411     25]
 [  1535    111]]
              precision    recall  f1-score   support

           0       1.00      1.00      1.00    552436
           1       0.82      0.07      0.12      1646

    accuracy                           1.00    554082
   macro avg       0.91      0.53      0.56    554082
weighted avg       1.00      1.00      1.00    554082



In [19]:
from sklearn.tree import DecisionTreeClassifier

# Model
dt = DecisionTreeClassifier()
dt.fit(X_train, y_train)

# Predictions
y_pred = dt.predict(X_test)

# Evaluation
print("Decision Tree Classifier")
print("Accuracy:", accuracy_score(y_test, y_pred))
print(confusion_matrix(y_test, y_pred))
print(classification_report(y_test, y_pred))

Decision Tree Classifier
Accuracy: 0.9973722301031255
[[551707    729]
 [   727    919]]
              precision    recall  f1-score   support

           0       1.00      1.00      1.00    552436
           1       0.56      0.56      0.56      1646

    accuracy                           1.00    554082
   macro avg       0.78      0.78      0.78    554082
weighted avg       1.00      1.00      1.00    554082



In [20]:
from sklearn.ensemble import RandomForestClassifier

# Model
rf = RandomForestClassifier()
rf.fit(X_train, y_train)

# Predictions
y_pred = rf.predict(X_test)

# Evaluation
print("Random Forest Classifier")
print("Accuracy:", accuracy_score(y_test, y_pred))
print(confusion_matrix(y_test, y_pred))
print(classification_report(y_test, y_pred))

Random Forest Classifier
Accuracy: 0.9980815114008396
[[552105    331]
 [   732    914]]
              precision    recall  f1-score   support

           0       1.00      1.00      1.00    552436
           1       0.73      0.56      0.63      1646

    accuracy                           1.00    554082
   macro avg       0.87      0.78      0.82    554082
weighted avg       1.00      1.00      1.00    554082



In [21]:
from sklearn.neighbors import KNeighborsClassifier

# Model
knn = KNeighborsClassifier()
knn.fit(X_train, y_train)

# Predictions
y_pred = knn.predict(X_test)

# Evaluation
print("K-Nearest Neighbors")
print("Accuracy:", accuracy_score(y_test, y_pred))
print(confusion_matrix(y_test, y_pred))
print(classification_report(y_test, y_pred))


K-Nearest Neighbors
Accuracy: 0.9983576438144535
[[552163    273]
 [   637   1009]]
              precision    recall  f1-score   support

           0       1.00      1.00      1.00    552436
           1       0.79      0.61      0.69      1646

    accuracy                           1.00    554082
   macro avg       0.89      0.81      0.84    554082
weighted avg       1.00      1.00      1.00    554082



In [22]:
from sklearn.ensemble import GradientBoostingClassifier

# Model
gbc = GradientBoostingClassifier()
gbc.fit(X_train, y_train)

# Predictions
y_pred = gbc.predict(X_test)

# Evaluation
print("Gradient Boosting Classifier")
print("Accuracy:", accuracy_score(y_test, y_pred))
print(confusion_matrix(y_test, y_pred))
print(classification_report(y_test, y_pred))


Gradient Boosting Classifier
Accuracy: 0.9974281785006551
[[552402     34]
 [  1391    255]]
              precision    recall  f1-score   support

           0       1.00      1.00      1.00    552436
           1       0.88      0.15      0.26      1646

    accuracy                           1.00    554082
   macro avg       0.94      0.58      0.63    554082
weighted avg       1.00      1.00      1.00    554082

